version: 2

sources:
  - name: taxi_raw              # source name used inside dbt
    database: TAXI_DB           # Snowflake database
    schema: RAW                 # Snowflake schema
    tables:
      - name: fhvhv_tripdata_ext_jan
        identifier: FHVHV_TRIPDATA_EXT_JAN   # actual table name in Snowflake

      - name: fhvhv_tripdata_ext_feb
        identifier: FHVHV_TRIPDATA_EXT_FEB

      - name: fhvhv_tripdata_ext_mar
        identifier: FHVHV_TRIPDATA_EXT_MAR

      - name: yellow_tripdata_ext_jan
        identifier: YELLOW_TRIPDATA_EXT_JAN

      - name: yellow_tripdata_ext_feb
        identifier: YELLOW_TRIPDATA_EXT_FEB

      - name: yellow_tripdata_ext_mar
        identifier: YELLOW_TRIPDATA_EXT_MAR
