taxi_data:
  outputs:
    dev:
      type: snowflake
      account: MXYSHJD-KU69407
      user: CPTRIPATHI

      role: dbt_role
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      
      database: Taxi_db
      schema: DEV
      threads: 4
      warehouse: dbt_wh
  target: dev